---

roles:
  - name: geerlingguy.apache
  - name: geerlingguy.certbot
  - name: geerlingguy.swap

collections:
  - name: amazon.aws
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1.1.1

