apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-sc
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: pd.csi.storage.gke.io
parameters:
  #type: "hyperdisk-balanced"
  type: pd-balanced
  #provisioned-iops-on-create: "3000"
  #provisioned-throughput-on-create: "150Mi"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
